language: csharp
solution: CnpSdkForNet.sln
notifications:
  email:
    - sdksupport@vantiv.com
dotnet: 2.1
install:
  - nuget restore CnpSdkForNet/CnpSdkForNet.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release CnpSdkForNet/CnpSdkForNet.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe CnpSdkForNet/CnpSdkForNetTest/bin/Release/netcoreapp2.1/CnpSdkForNetTest.dll
after_success:
 - bash <(curl -s https://codecov.io/bash)
  
